name: PublishNugets

on: 
  workflow_dispatch:

jobs:
  build:
    name: nugets-ubuntu
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.x
        
    - name: Restore dependencies
      run: dotnet restore source/gpm.sln
    - name: Build
      run: dotnet build source/gpm.sln --no-restore

      
    - name: publish nuget
      id: publish_nuget
      uses: rohith/publish-nuget@v2
      with:
        PROJECT_FILE_PATH: source/gpm/gpm.csproj
        NUGET_KEY: ${{secrets.NUGET_KEY}}
    - name: publish core nuget
      id: publish_nuget_core
      uses: rohith/publish-nuget@v2
      with:
        PROJECT_FILE_PATH: source/gpm.Core/gpm.Core.csproj
        NUGET_KEY: ${{secrets.NUGET_KEY}}

