name: Release

on: 
  push:
    tags:
    - '*'

jobs:
  build:
    name: release-win
    runs-on: windows-2022
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.x
    - name: Restore dependencies
      run: dotnet restore source/gpm.sln
    - name: Build
      run: dotnet build source/gpm.sln --no-restore
      
    - name: Publish
      run: dotnet publish source/gpm/gpm.csproj -o publish-win # && dotnet publish source/gpm/gpm.csproj -r linux-x64 --no-self-contained -o publish-linux
    # - uses: montudor/action-zip@v1
    #  with:
    #    args: zip -qq -r gpm-win.zip publish-win/ 
    #- uses: montudor/action-zip@v1
    #  with:
    #    args: zip -qq -r gpm-linux.zip publish-linux/
    - run: Compress-Archive -Path publish-win\* -DestinationPath gpm-win.zip
    
    - uses: ncipollo/release-action@v1
      with:
        draft: true
        generateReleaseNotes: true
        artifacts: "*.zip"
#        bodyFile: "body.md"
        token: ${{ secrets.GITHUB_TOKEN }}

    - name: publish nuget
      id: publish_nuget
      uses: rohith/publish-nuget@v2
      with:
        PROJECT_FILE_PATH: source/gpm/gpm.csproj
        NUGET_KEY: ${{secrets.NUGET_KEY}}

